//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CameraSystem.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CM_Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CM_Account()
        {
            this.CM_Roles = new HashSet<CM_Roles>();
        }
    
        public System.Guid Id { get; set; }
        public string GEN { get; set; }
        public string full_name { get; set; }
        public string password { get; set; }
        public Nullable<bool> approved { get; set; }
        public string email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CM_Roles> CM_Roles { get; set; }
    }
}
