//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CameraSystem.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CM_AVI_Log
    {
        public System.Guid id { get; set; }
        public string ip { get; set; }
        public string machine { get; set; }
        public string model { get; set; }
        public Nullable<System.DateTime> test_time { get; set; }
        public Nullable<double> duration_time { get; set; }
        public string result { get; set; }
        public Nullable<int> quantity_dust { get; set; }
        public string parameter { get; set; }
        public string version { get; set; }
        public string detail { get; set; }
    }
}
