//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CameraSystem.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CM_FTP_Log
    {
        public System.Guid id { get; set; }
        public string ftp_log { get; set; }
        public string detail { get; set; }
        public Nullable<int> lineId { get; set; }
        public Nullable<int> machineId { get; set; }
        public Nullable<System.DateTime> INPUT_time { get; set; }
        public Nullable<int> column_count { get; set; }
    }
}
