//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CameraSystem.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CM_Machine_DLL
    {
        public System.Guid id { get; set; }
        public Nullable<int> machineId { get; set; }
        public string file_name { get; set; }
        public string file_version { get; set; }
        public string file_location { get; set; }
        public Nullable<System.DateTime> update_time { get; set; }
        public string update_id { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public Nullable<System.DateTime> modify_time { get; set; }
    }
}
