//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CameraSystem.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CM_ModelChange
    {
        public int id { get; set; }
        public int lineId { get; set; }
        public int modelId { get; set; }
        public string userId { get; set; }
        public System.DateTime datetimechange { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> datetimestop { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
