//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CameraSystem.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CM_Model
    {
        public int id { get; set; }
        public string name { get; set; }
        public string code { get; set; }
        public Nullable<int> projectId { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
    }
}
