//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CameraSystem.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QM_DualCal
    {
        public long table_id { get; set; }
        public string line { get; set; }
        public string machine_id { get; set; }
        public string process { get; set; }
        public string port { get; set; }
        public string file_name { get; set; }
        public string module_id { get; set; }
        public Nullable<System.DateTime> test_time { get; set; }
        public string pass_fail { get; set; }
        public string af_code_w { get; set; }
        public string ois_origin_wx { get; set; }
        public string shift_wx { get; set; }
        public string shift_result_wx { get; set; }
        public string dev_wx { get; set; }
        public string ois_origin_wy { get; set; }
        public string shift_wy { get; set; }
        public string shift_result_wy { get; set; }
        public string dev_wy { get; set; }
        public string mce_x { get; set; }
        public string offset_x { get; set; }
        public string new_x { get; set; }
        public string new_x_read { get; set; }
        public string mce_y { get; set; }
        public string offset_y { get; set; }
        public string new_y { get; set; }
        public string new_y_read { get; set; }
        public string af_code_t { get; set; }
        public string ois_origin_tx { get; set; }
        public string shift_tx { get; set; }
        public string shift_result_tx { get; set; }
        public string dev_tx { get; set; }
        public string ois_origin_ty { get; set; }
        public string shift_ty { get; set; }
        public string shift_result_ty { get; set; }
        public string dev_ty { get; set; }
        public string mce_ty { get; set; }
        public string mce_x_1 { get; set; }
        public string offset_x_1 { get; set; }
        public string new_x_1 { get; set; }
        public string new_x_read_1 { get; set; }
        public string mce_y_1 { get; set; }
        public string offset_y_1 { get; set; }
        public string new_y_1 { get; set; }
        public string new_y_read_1 { get; set; }
        public string ori_rx { get; set; }
        public string ori_ry { get; set; }
        public string ori_rz { get; set; }
        public string ori_shift_x { get; set; }
        public string ori_shift_y { get; set; }
        public string crop_no { get; set; }
        public string final_rx { get; set; }
        public string final_ry { get; set; }
        public string final_rz { get; set; }
        public string final_shift_x { get; set; }
        public string final_shift_y { get; set; }
        public string sx_min { get; set; }
        public string sx_max { get; set; }
        public string sy_min { get; set; }
        public string sy_max { get; set; }
        public string diff_x { get; set; }
        public string diff_y { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public Nullable<int> modelId { get; set; }
    }
}
