//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CameraSystem.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QM_FT_50cm_Tele
    {
        public long table_id { get; set; }
        public string module_id { get; set; }
        public string line { get; set; }
        public string port { get; set; }
        public string machine_id { get; set; }
        public string process { get; set; }
        public string file_name { get; set; }
        public string socket { get; set; }
        public string mode { get; set; }
        public string w_t { get; set; }
        public Nullable<System.DateTime> test_time { get; set; }
        public string pass_fail { get; set; }
        public string from100cm { get; set; }
        public string from50cm { get; set; }
        public string real50cm { get; set; }
        public string c0 { get; set; }
        public string c1 { get; set; }
        public string c2 { get; set; }
        public string c3 { get; set; }
        public string c5 { get; set; }
        public string c6 { get; set; }
        public string c13 { get; set; }
        public string c14 { get; set; }
        public string c18 { get; set; }
        public string c19 { get; set; }
        public string c26 { get; set; }
        public string c27 { get; set; }
        public string c31 { get; set; }
        public string c32 { get; set; }
        public string c33 { get; set; }
        public string c34 { get; set; }
        public string c38 { get; set; }
        public string c39 { get; set; }
        public string c40 { get; set; }
        public string c41 { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public Nullable<int> modelId { get; set; }
    }
}
