//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CameraSystem.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QM_PAF_AE_Cal_Ratio
    {
        public long table_id { get; set; }
        public string no { get; set; }
        public string line { get; set; }
        public string machine_id { get; set; }
        public string process { get; set; }
        public string port { get; set; }
        public string file_name { get; set; }
        public string module_id { get; set; }
        public string pass_fail { get; set; }
        public Nullable<System.DateTime> test_time { get; set; }
        public string ae_ratio { get; set; }
        public string percent { get; set; }
        public string master_exp_time { get; set; }
        public string f1_5_Exp_Time { get; set; }
        public string mclk { get; set; }
        public string vt_pix { get; set; }
        public string vt_sys { get; set; }
        public string pre_pll { get; set; }
        public string pll_multi { get; set; }
        public string pll_s { get; set; }
        public string line_length { get; set; }
        public string coarese_integration_time { get; set; }
        public string r_avg { get; set; }
        public string gr_avg { get; set; }
        public string gb_avg { get; set; }
        public string b_avg { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public Nullable<int> modelId { get; set; }
    }
}
