//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CameraSystem.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QM_PAF_Handler
    {
        public long table_id { get; set; }
        public string line { get; set; }
        public string machine_id { get; set; }
        public string process { get; set; }
        public string file_name { get; set; }
        public Nullable<System.DateTime> test_time { get; set; }
        public string pass_fail { get; set; }
        public string socket { get; set; }
        public string site_a_result { get; set; }
        public string site_b_result { get; set; }
        public string site_c_result { get; set; }
        public string site_d_result { get; set; }
        public string cycle_time { get; set; }
        public string site_a_tt { get; set; }
        public string site_b_tt { get; set; }
        public string site_c_tt { get; set; }
        public string site_d_tt { get; set; }
        public string retry { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public string type { get; set; }
        public Nullable<int> modelId { get; set; }
        public string port { get; set; }
    }
}
