//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Check_Application
    {
        public long id_process { get; set; }
        public Nullable<int> line { get; set; }
        public string process { get; set; }
        public Nullable<bool> status { get; set; }
    }
}
