//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CM_Line
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> zoneId { get; set; }
        public Nullable<int> modelId { get; set; }
        public string line_group { get; set; }
    }
}
