//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MACHINE_QUANTITY_SCREEN
    {
        public string model { get; set; }
        public string process { get; set; }
        public string line { get; set; }
        public string machine { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> hour { get; set; }
        public Nullable<int> qty { get; set; }
    }
}
