//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QM_Ois
    {
        public long table_id { get; set; }
        public string module_id { get; set; }
        public string line { get; set; }
        public string machine_id { get; set; }
        public string process { get; set; }
        public string port { get; set; }
        public string file_name { get; set; }
        public string socket { get; set; }
        public string pass_fail { get; set; }
        public string code { get; set; }
        public string desc { get; set; }
        public Nullable<System.DateTime> test_time { get; set; }
        public Nullable<System.DateTime> end_time { get; set; }
        public string front_Time { get; set; }
        public string rear_Time { get; set; }
        public string total_Time { get; set; }
        public string f_w_ver { get; set; }
        public string aF_Chip_Tpye { get; set; }
        public string pos_Cal { get; set; }
        public string neg_Cal { get; set; }
        public string aF_Code { get; set; }
        public string x_Hall_Max { get; set; }
        public string x_Hall_Min { get; set; }
        public string x_Hall_Center { get; set; }
        public string x_d_r { get; set; }
        public string x_Hall_Bias { get; set; }
        public string x_Hall_Offset { get; set; }
        public string y_Hall_Max { get; set; }
        public string y_Hall_Min { get; set; }
        public string y_Hall_Center { get; set; }
        public string y_d_r { get; set; }
        public string y_Hall_Bias { get; set; }
        public string y_Hall_Offset { get; set; }
        public string gyro_Offset_X { get; set; }
        public string gyro_Offset_Y { get; set; }
        public string x_K9B { get; set; }
        public string y_K9B { get; set; }
        public string x_10Hz_Gain { get; set; }
        public string y_10Hz_Gain { get; set; }
        public string x_Phase_Margin { get; set; }
        public string y_Phase_Margin { get; set; }
        public string pan_Code_Move { get; set; }
        public string shiftDiff_X { get; set; }
        public string shiftDiff_Y { get; set; }
        public string gyro_Gain_X { get; set; }
        public string gyro_Gain_Y { get; set; }
        public string oIS_Off_X { get; set; }
        public string oIS_Off_Y { get; set; }
        public string sR_X { get; set; }
        public string sR_Y { get; set; }
        public string sR_X_Low_Freq { get; set; }
        public string sR_Y_Low_Freq { get; set; }
        public string sR_X_High_Freq { get; set; }
        public string sR_Y_High_Freq { get; set; }
        public string sin_Wave_X { get; set; }
        public string sin_Wave_Y { get; set; }
        public string sin_Count_X_up { get; set; }
        public string sin_Abs_X_up { get; set; }
        public string sin_Count_Y_up { get; set; }
        public string sin_Abs_Y_up { get; set; }
        public string sin_Result_up { get; set; }
        public string settling_Time_Xs_up { get; set; }
        public string settling_Time_Y_up { get; set; }
        public string settling_Result_up { get; set; }
        public string sin_Count_X_Front { get; set; }
        public string sin_Abs_X_Front { get; set; }
        public string sin_Count_Y_Front { get; set; }
        public string sin_Abs_Y_Front { get; set; }
        public string sin_Result_Front { get; set; }
        public string settling_Time_X_Front { get; set; }
        public string settling_Time_Y_Front { get; set; }
        public string settling_Result_Front { get; set; }
        public string sin_Count_X_Final { get; set; }
        public string sin_Abs_X_Final { get; set; }
        public string sin_Count_Y_Final { get; set; }
        public string sin_Abs_Y_Final { get; set; }
        public string sin_Result_Final { get; set; }
        public string settling_Time_X_Final { get; set; }
        public string settling_Time_Y_Final { get; set; }
        public string settling_Result_Final { get; set; }
        public string aF_Code_Tele { get; set; }
        public string x_Hall_Maxx_Tele { get; set; }
        public string x_Hall_Minx_Tele { get; set; }
        public string x_Hall_Center_Tele { get; set; }
        public string x_D_R_Tele { get; set; }
        public string x_Hall_Bias_Tele { get; set; }
        public string x_Hall_Offset_Tele { get; set; }
        public string y_Hall_Max_Tele { get; set; }
        public string y_Hall_Min_Tele { get; set; }
        public string y_Hall_Center_Tele { get; set; }
        public string y_D_R_Tele { get; set; }
        public string y_Hall_Bias_Tele { get; set; }
        public string y_Hall_Offset_Tele { get; set; }
        public string x_K9B_Tele { get; set; }
        public string y_K9B_Tele { get; set; }
        public string x_10Hz_Gain_Tele { get; set; }
        public string y_10Hz_Gain_Tele { get; set; }
        public string x_Phase_Margin_Tele { get; set; }
        public string y_Phase_Margin_Tele { get; set; }
        public string pan_Code_Move_Tele { get; set; }
        public string shiftDiff_X_Tele { get; set; }
        public string shiftDiff_Y_Tele { get; set; }
        public string gyro_Gain_X_Tele { get; set; }
        public string gyro_Gain_Y_Tele { get; set; }
        public string ois_Off_X_Tele { get; set; }
        public string ois_Off_Y_Tele { get; set; }
        public string sr_X_Tele { get; set; }
        public string sr_YTele { get; set; }
        public string sin_Count_X_up_Tele { get; set; }
        public string sin_Abs_X_up_Tele { get; set; }
        public string sin_Count_Y_up_Tele { get; set; }
        public string sin_Abs_Y_up_Tele { get; set; }
        public string sin_Result_up_Tele { get; set; }
        public string settling_Time_X_up_Tele { get; set; }
        public string settling_Time_Y_up_Tele { get; set; }
        public string settling_Result_up_Tele { get; set; }
        public string sin_Count_X_Front_Tele { get; set; }
        public string sin_Abs_X_Front_Tele { get; set; }
        public string sin_Count_Y_Front_Tele { get; set; }
        public string sin_Abs_Y_Front_Tele { get; set; }
        public string sin_Result_Front_Tele { get; set; }
        public string settling_Time_X_Front_Tele { get; set; }
        public string settling_Time_Y_Front_Tele { get; set; }
        public string settling_Result_Front_Tele { get; set; }
        public string sin_Count_X_Final_Tele { get; set; }
        public string sin_Abs_X_Final_Tele { get; set; }
        public string sin_Count_Y_Final_Tele { get; set; }
        public string sin_Abs_Y_Final_Tele { get; set; }
        public string sin_Result_Final_Tele { get; set; }
        public string settling_time_X_Final_Tele { get; set; }
        public string settling_Time_Y_Final_Tele { get; set; }
        public string settling_Result_Final_Tele { get; set; }
        public string dvdd1_2v { get; set; }
        public string dvdd1_8v { get; set; }
        public string ois2_8v { get; set; }
        public string af2_8v { get; set; }
        public string vdda2_8v { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public Nullable<int> modelId { get; set; }
    }
}
