//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QTY_OF_LINE_BY_PROCESS_ON_DATE_SCREEN
    {
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> hour { get; set; }
        public string process { get; set; }
        public string line { get; set; }
        public string port { get; set; }
        public string socket { get; set; }
        public Nullable<int> qty { get; set; }
    }
}
