//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_MACHINE_STATUS
    {
        public string MODEL { get; set; }
        public Nullable<int> LINE { get; set; }
        public int MACHINE_ID { get; set; }
        public string IP { get; set; }
        public string PROCE { get; set; }
        public string M_STATUS { get; set; }
    }
}
