//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_TABLESIZE2
    {
        public string filegroupname { get; set; }
        public string FileName { get; set; }
        public string PhysicalName { get; set; }
        public Nullable<int> TotalSizeinMB { get; set; }
        public Nullable<decimal> AvailableSpaceInMB { get; set; }
        public Nullable<decimal> ActualSpaceUsedInMB { get; set; }
        public Nullable<decimal> C_SpaceUsed { get; set; }
    }
}
