//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_TABLESIZE
    {
        public string TableName { get; set; }
        public string SchemaName { get; set; }
        public long RowCounts { get; set; }
        public Nullable<long> TotalSpaceKB { get; set; }
        public Nullable<decimal> TotalSpaceMB { get; set; }
        public Nullable<long> UsedSpaceKB { get; set; }
        public Nullable<decimal> UsedSpaceMB { get; set; }
        public Nullable<long> UnusedSpaceKB { get; set; }
        public Nullable<decimal> UnusedSpaceMB { get; set; }
    }
}
