//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_TESTRESULTNG
    {
        public string ModuleID { get; set; }
        public Nullable<System.DateTime> Test_Time { get; set; }
        public string Model_Name { get; set; }
        public string Process_Name { get; set; }
        public string Line_Name { get; set; }
        public string Socket { get; set; }
    }
}
